FROM node:22-alpine@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32 AS base
RUN npm install --global npm@11.19.0
WORKDIR /app
COPY package*.json ./
COPY apps/web/package.json apps/web/package.json
COPY apps/api/package.json apps/api/package.json
COPY apps/worker/package.json apps/worker/package.json
COPY packages/shared/package.json packages/shared/package.json
COPY packages/authjs/package.json packages/authjs/package.json
COPY packages/authjs-core/package.json packages/authjs-core/package.json
COPY packages/pptxgenjs/package.json packages/pptxgenjs/package.json
RUN npm ci
COPY . .
RUN npm run prisma:generate
RUN npm run build -w @studydeck/shared
RUN npm run build -w @studydeck/api
RUN npm prune --omit=dev

FROM node:22-alpine@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32 AS runner
RUN npm install --global npm@11.19.0
WORKDIR /app
ENV NODE_ENV=production
COPY --chown=node:node --from=base /app/package*.json ./
COPY --chown=node:node --from=base /app/node_modules ./node_modules
COPY --chown=node:node --from=base /app/prisma ./prisma
COPY --chown=node:node --from=base /app/packages/shared ./packages/shared
COPY --chown=node:node --from=base /app/apps/api ./apps/api
USER node
EXPOSE 4000
CMD ["npm", "run", "start", "-w", "@studydeck/api"]
