import {
  presentationSchema,
  PREMIUM_PRESENTATION_THEMES,
  type PresentationDocument,
} from "@studydeck/shared";

export type LandingShowcaseFixtureId =
  | "ai-education"
  | "cuban-missile-crisis"
  | "renewable-energy";

export type LandingShowcaseCover = {
  src: `/landing/${string}`;
  alt: string;
  caption: string;
};

export type LandingShowcaseFixture = {
  id: LandingShowcaseFixtureId;
  cover: LandingShowcaseCover;
  presentation: PresentationDocument;
};

function defineLandingShowcaseFixture(fixture: LandingShowcaseFixture): LandingShowcaseFixture {
  return {
    ...fixture,
    presentation: presentationSchema.parse(fixture.presentation),
  };
}

export const LANDING_SHOWCASE_FIXTURES: readonly LandingShowcaseFixture[] = [
  defineLandingShowcaseFixture({
    id: "ai-education",
    cover: {
      src: "/landing/ai-education/lecture-hall.webp",
      alt: "Студенты работают с цифровыми учебными материалами в современной аудитории",
      caption: "ИИ в образовании: персональная траектория и обратная связь",
    },
    presentation: {
      id: "landing-ai-education",
      title: "Как искусственный интеллект меняет образование",
      scenario: "university_report",
      level: "university_student",
      slideCount: 4,
      generationMode: "demo",
      generatedText: "",
      sources: [],
      outline: [
        "ИИ как помощник студента",
        "Как строится персональная траектория",
        "Роль преподавателя остаётся ключевой",
        "Вывод",
      ],
      narrativePlan: [],
      presentationTheme: PREMIUM_PRESENTATION_THEMES.darkLecture,
      speechScript: [
        {
          slideOrder: 1,
          slideTitle: "Как искусственный интеллект меняет образование",
          text: "ИИ не заменяет обучение: он помогает быстрее увидеть пробелы, подобрать практику и подготовиться к защите.",
        },
        {
          slideOrder: 2,
          slideTitle: "Персональная траектория",
          text: "Система собирает материал, предлагает объяснение и даёт студенту понятную следующую задачу.",
        },
        {
          slideOrder: 3,
          slideTitle: "Человек остаётся в центре",
          text: "Технология ускоряет рутину, а преподаватель помогает проверять аргументы и обсуждать сложные решения.",
        },
        {
          slideOrder: 4,
          slideTitle: "Вывод",
          text: "Сильный результат появляется, когда ИИ расширяет возможности студента, а не делает работу за него.",
        },
      ],
      slides: [
        {
          id: "landing-ai-education-1",
          order: 1,
          title: "Как искусственный интеллект меняет образование",
          slideKind: "title",
          layout: "hero",
          thesis: "От общей темы — к понятной структуре, аргументам и готовой речи для защиты.",
          bullets: ["Персональная практика", "Быстрая обратная связь", "Подготовка к выступлению"],
          definition: null,
          keyConcepts: [],
          visual: { type: "none", title: "", description: "", leftLabel: "", rightLabel: "", items: [], rows: [] },
          highlights: [],
          blocks: [{ type: "callout", content: "ИИ помогает студенту работать с материалом осмысленно и последовательно." }],
          speakerNotes: "ИИ не заменяет обучение: он помогает быстрее увидеть пробелы, подобрать практику и подготовиться к защите.",
          timingSeconds: 35,
          sourceRefs: [],
        },
        {
          id: "landing-ai-education-2",
          order: 2,
          title: "Персональная траектория",
          slideKind: "content",
          layout: "process",
          thesis: "Полезный помощник не выдаёт ответ сразу, а ведёт от материала к собственному объяснению.",
          bullets: ["Собрать контекст", "Объяснить сложное", "Проверить понимание"],
          definition: null,
          keyConcepts: [],
          visual: {
            type: "process_diagram",
            title: "",
            description: "",
            leftLabel: "",
            rightLabel: "",
            items: [
              { label: "Материал", text: "Конспект, статья или тема" },
              { label: "Разбор", text: "План, примеры и вопросы" },
              { label: "Выступление", text: "Своя аргументация и речь" },
            ],
            rows: [],
          },
          highlights: [],
          blocks: [{ type: "bullets", items: ["Собрать контекст", "Объяснить сложное", "Проверить понимание"] }],
          speakerNotes: "Система собирает материал, предлагает объяснение и даёт студенту понятную следующую задачу.",
          timingSeconds: 40,
          sourceRefs: [],
        },
        {
          id: "landing-ai-education-3",
          order: 3,
          title: "Человек остаётся в центре",
          slideKind: "content",
          layout: "comparison",
          thesis: "Лучший учебный сценарий распределяет роли между технологией и преподавателем.",
          bullets: ["ИИ ускоряет подготовку", "Преподаватель задаёт критерии", "Студент формулирует позицию"],
          definition: null,
          keyConcepts: [],
          visual: {
            type: "comparison_diagram",
            title: "",
            description: "",
            leftLabel: "ИИ-помощник",
            rightLabel: "Преподаватель",
            items: [],
            rows: [
              { label: "Рутина", left: "Собирает и структурирует", right: "Определяет цель" },
              { label: "Проверка", left: "Подсвечивает пробелы", right: "Оценивает аргументы" },
              { label: "Развитие", left: "Предлагает практику", right: "Даёт содержательную обратную связь" },
            ],
          },
          highlights: [],
          blocks: [{ type: "bullets", items: ["ИИ ускоряет подготовку", "Преподаватель задаёт критерии", "Студент формулирует позицию"] }],
          speakerNotes: "Технология ускоряет рутину, а преподаватель помогает проверять аргументы и обсуждать сложные решения.",
          timingSeconds: 40,
          sourceRefs: [],
        },
        {
          id: "landing-ai-education-4",
          order: 4,
          title: "Вывод",
          slideKind: "summary",
          layout: "summary",
          thesis: "ИИ делает подготовку гибче, если студент остаётся автором работы и выступления.",
          bullets: ["Тема превращается в маршрут", "Материал становится понятнее", "Речь остаётся собственной"],
          definition: null,
          keyConcepts: [],
          visual: { type: "none", title: "", description: "", leftLabel: "", rightLabel: "", items: [], rows: [] },
          highlights: [],
          blocks: [{ type: "bullets", items: ["Тема превращается в маршрут", "Материал становится понятнее", "Речь остаётся собственной"] }],
          speakerNotes: "Сильный результат появляется, когда ИИ расширяет возможности студента, а не делает работу за него.",
          timingSeconds: 35,
          sourceRefs: [],
        },
      ],
    },
  }),
  defineLandingShowcaseFixture({
    id: "cuban-missile-crisis",
    cover: {
      src: "/landing/caribbean-crisis/map-room.webp",
      alt: "Архивная фотография морского патруля времён Карибского кризиса",
      caption: "Карибский кризис: решения, которые отвели мир от ядерной войны",
    },
    presentation: {
      id: "landing-cuban-missile-crisis",
      title: "Причины и последствия Карибского кризиса",
      scenario: "university_report",
      level: "university_student",
      slideCount: 4,
      generationMode: "demo",
      generatedText: "",
      sources: [],
      outline: ["Осень 1962 года", "Тринадцать дней напряжения", "Выбор между эскалацией и переговорами", "Последствия"],
      narrativePlan: [],
      presentationTheme: PREMIUM_PRESENTATION_THEMES.timelineDocumentary,
      speechScript: [
        {
          slideOrder: 1,
          slideTitle: "Причины и последствия Карибского кризиса",
          text: "Осенью 1962 года противостояние СССР и США оказалось ближе всего к прямому ядерному столкновению.",
        },
        {
          slideOrder: 2,
          slideTitle: "Тринадцать дней",
          text: "Кризис развивался стремительно: от обнаружения ракет на Кубе до публичных переговоров и компромисса.",
        },
        {
          slideOrder: 3,
          slideTitle: "Эскалация или переговоры",
          text: "Решение зависело не только от силы, но и от способности сохранить канал связи между противниками.",
        },
        {
          slideOrder: 4,
          slideTitle: "Последствия",
          text: "После кризиса сверхдержавы начали создавать механизмы, которые снижают риск случайной эскалации.",
        },
      ],
      slides: [
        {
          id: "landing-cuban-missile-crisis-1",
          order: 1,
          title: "Причины и последствия Карибского кризиса",
          slideKind: "title",
          layout: "hero",
          thesis: "Осень 1962 года показала, насколько опасным может стать конфликт без прямого диалога.",
          bullets: ["СССР", "США", "Куба"],
          definition: null,
          keyConcepts: [],
          visual: { type: "none", title: "", description: "", leftLabel: "", rightLabel: "", items: [], rows: [] },
          highlights: [],
          blocks: [{ type: "callout", content: "Три государства оказались в центре решения, от которого зависела мировая безопасность." }],
          speakerNotes: "Осенью 1962 года противостояние СССР и США оказалось ближе всего к прямому ядерному столкновению.",
          timingSeconds: 35,
          sourceRefs: [],
        },
        {
          id: "landing-cuban-missile-crisis-2",
          order: 2,
          title: "Тринадцать дней",
          slideKind: "content",
          layout: "timeline",
          thesis: "Ключевые события уложились меньше чем в две недели, но изменили правила международной безопасности.",
          bullets: ["14 октября", "22 октября", "28 октября"],
          definition: null,
          keyConcepts: [],
          visual: {
            type: "timeline",
            title: "",
            description: "",
            leftLabel: "",
            rightLabel: "",
            items: [
              { label: "14 октября", text: "Аэрофотосъёмка подтверждает размещение советских ракет на Кубе" },
              { label: "22 октября", text: "Джон Кеннеди объявляет морской карантин Кубы" },
              { label: "28 октября", text: "СССР соглашается демонтировать ракеты" },
            ],
            rows: [],
          },
          highlights: [],
          blocks: [{ type: "bullets", items: ["14 октября", "22 октября", "28 октября"] }],
          speakerNotes: "Кризис развивался стремительно: от обнаружения ракет на Кубе до публичных переговоров и компромисса.",
          timingSeconds: 45,
          sourceRefs: [],
        },
        {
          id: "landing-cuban-missile-crisis-3",
          order: 3,
          title: "Эскалация или переговоры",
          slideKind: "content",
          layout: "comparison",
          thesis: "Военный ответ и дипломатический путь несли разные риски для всех участников конфликта.",
          bullets: ["Блокада дала время", "Связь снизила риск ошибки", "Компромисс сохранил лицо сторонам"],
          definition: null,
          keyConcepts: [],
          visual: {
            type: "comparison_diagram",
            title: "",
            description: "",
            leftLabel: "Эскалация",
            rightLabel: "Переговоры",
            items: [],
            rows: [
              { label: "Темп", left: "Быстрые необратимые шаги", right: "Время на проверку решений" },
              { label: "Риск", left: "Ответный удар и расширение конфликта", right: "Сложный, но управляемый компромисс" },
              { label: "Результат", left: "Непредсказуемая цена", right: "Снижение непосредственной угрозы" },
            ],
          },
          highlights: [],
          blocks: [{ type: "bullets", items: ["Блокада дала время", "Связь снизила риск ошибки", "Компромисс сохранил лицо сторонам"] }],
          speakerNotes: "Решение зависело не только от силы, но и от способности сохранить канал связи между противниками.",
          timingSeconds: 45,
          sourceRefs: [],
        },
        {
          id: "landing-cuban-missile-crisis-4",
          order: 4,
          title: "Последствия",
          slideKind: "summary",
          layout: "summary",
          thesis: "Кризис стал уроком о ценности прямой связи, контроля вооружений и времени для дипломатии.",
          bullets: ["Появилась горячая линия", "Усилился контроль вооружений", "Компромисс стал частью стратегии"],
          definition: null,
          keyConcepts: [],
          visual: { type: "none", title: "", description: "", leftLabel: "", rightLabel: "", items: [], rows: [] },
          highlights: [],
          blocks: [{ type: "bullets", items: ["Появилась горячая линия", "Усилился контроль вооружений", "Компромисс стал частью стратегии"] }],
          speakerNotes: "После кризиса сверхдержавы начали создавать механизмы, которые снижают риск случайной эскалации.",
          timingSeconds: 35,
          sourceRefs: [],
        },
      ],
    },
  }),
  defineLandingShowcaseFixture({
    id: "renewable-energy",
    cover: {
      src: "/landing/future-energy/city.webp",
      alt: "Современные солнечные панели и ветрогенераторы рядом с городской застройкой",
      caption: "Энергия будущего: генерация, накопление и умная городская сеть",
    },
    presentation: {
      id: "landing-renewable-energy",
      title: "Возобновляемая энергетика и города будущего",
      scenario: "university_report",
      level: "university_student",
      slideCount: 4,
      generationMode: "demo",
      generatedText: "",
      sources: [],
      outline: ["Город как энергосистема", "Что меняет возобновляемая генерация", "Три опоры устойчивой сети", "Вывод"],
      narrativePlan: [],
      presentationTheme: PREMIUM_PRESENTATION_THEMES.scienceBoard,
      speechScript: [
        {
          slideOrder: 1,
          slideTitle: "Возобновляемая энергетика и города будущего",
          text: "Город будущего не просто потребляет энергию: он умеет производить, хранить и распределять её точнее.",
        },
        {
          slideOrder: 2,
          slideTitle: "Город как энергосистема",
          text: "Солнечные панели, ветер и накопители работают не по отдельности, а как связанная инфраструктура.",
        },
        {
          slideOrder: 3,
          slideTitle: "Три опоры устойчивой сети",
          text: "Устойчивость создаёт не один источник, а согласованная работа генерации, накопления и управления спросом.",
        },
        {
          slideOrder: 4,
          slideTitle: "Вывод",
          text: "Технологии становятся городскими решениями, когда помогают сделать среду чище, устойчивее и удобнее для жителей.",
        },
      ],
      slides: [
        {
          id: "landing-renewable-energy-1",
          order: 1,
          title: "Возобновляемая энергетика и города будущего",
          slideKind: "title",
          layout: "hero",
          thesis: "Чистая энергия становится частью городской инфраструктуры, а не отдельным экспериментом.",
          bullets: ["Солнце", "Ветер", "Накопители"],
          definition: null,
          keyConcepts: [],
          visual: { type: "none", title: "", description: "", leftLabel: "", rightLabel: "", items: [], rows: [] },
          highlights: [],
          blocks: [{ type: "callout", content: "Городу нужна не только генерация, но и умное управление энергией." }],
          speakerNotes: "Город будущего не просто потребляет энергию: он умеет производить, хранить и распределять её точнее.",
          timingSeconds: 35,
          sourceRefs: [],
        },
        {
          id: "landing-renewable-energy-2",
          order: 2,
          title: "Город как энергосистема",
          slideKind: "content",
          layout: "process",
          thesis: "Возобновляемая генерация становится надёжнее, когда её связывают с хранением и управлением нагрузкой.",
          bullets: ["Произвести", "Сохранить", "Распределить"],
          definition: null,
          keyConcepts: [],
          visual: {
            type: "process_diagram",
            title: "",
            description: "",
            leftLabel: "",
            rightLabel: "",
            items: [
              { label: "Генерация", text: "Солнце и ветер дают энергию в разное время" },
              { label: "Накопление", text: "Батареи сохраняют избыток" },
              { label: "Сеть", text: "Умное распределение покрывает спрос" },
            ],
            rows: [],
          },
          highlights: [],
          blocks: [{ type: "bullets", items: ["Произвести", "Сохранить", "Распределить"] }],
          speakerNotes: "Солнечные панели, ветер и накопители работают не по отдельности, а как связанная инфраструктура.",
          timingSeconds: 40,
          sourceRefs: [],
        },
        {
          id: "landing-renewable-energy-3",
          order: 3,
          title: "Три опоры устойчивой сети",
          slideKind: "content",
          layout: "metrics",
          thesis: "Надёжная энергетика города складывается из трёх взаимосвязанных уровней.",
          bullets: ["3 источника гибкости: генерация, накопление, управление", "24/7 баланс спроса и предложения", "1 городская сеть вместо разрозненных решений"],
          definition: null,
          keyConcepts: [],
          visual: {
            type: "schema",
            title: "",
            description: "",
            leftLabel: "",
            rightLabel: "",
            items: [
              { label: "Генерация", text: "" },
              { label: "Накопление", text: "" },
              { label: "Управление", text: "" },
            ],
            rows: [],
          },
          highlights: [],
          blocks: [{ type: "bullets", items: ["3 источника гибкости: генерация, накопление, управление", "24/7 баланс спроса и предложения", "1 городская сеть вместо разрозненных решений"] }],
          speakerNotes: "Устойчивость создаёт не один источник, а согласованная работа генерации, накопления и управления спросом.",
          timingSeconds: 40,
          sourceRefs: [],
        },
        {
          id: "landing-renewable-energy-4",
          order: 4,
          title: "Вывод",
          slideKind: "summary",
          layout: "summary",
          thesis: "Возобновляемая энергетика меняет город тогда, когда становится частью повседневной жизни жителей.",
          bullets: ["Чище воздух", "Устойчивее инфраструктура", "Больше контроля у города и жителей"],
          definition: null,
          keyConcepts: [],
          visual: { type: "none", title: "", description: "", leftLabel: "", rightLabel: "", items: [], rows: [] },
          highlights: [],
          blocks: [{ type: "bullets", items: ["Чище воздух", "Устойчивее инфраструктура", "Больше контроля у города и жителей"] }],
          speakerNotes: "Технологии становятся городскими решениями, когда помогают сделать среду чище, устойчивее и удобнее для жителей.",
          timingSeconds: 35,
          sourceRefs: [],
        },
      ],
    },
  }),
];
